let suggestions = [
    "Aurora",
    "Volcanoes",
    "Mountains",
    "Hills",
    "Canopy",
    "Rainforest",
    "Valley",
    "Oceans",
    "YouTuber",
    "CodingNepal",
    "ProgrammingWithMosh",
    "Clever Programmer",
    "CsDojo",
    "CoderCoder",
    "WebDevSimplified",
    "JimCodes",
    "How To create a YouTube Channel",
    "How to mask a password in C++?",
    "How to create a search Engine ,vanilla javascript?",
    "How To learn Duestch in 5 months",
    "How to make good tutorials",
    "How to make money online?",
    "Is it possible to get a job without a degree in CS?",
    "How much do Javscript developers make?",
    "Is it possible to learn web dev in 3months?",
    "Is game development still relevant?",
    "Which game engine was used to create GTA SANANDREAS?",
    "How Rich is Elon Musk?",
    "Which country has the Best Programmers in The world?",
]